SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM((PRICE) * SALES_CNT) AS TOTAL_SALES
FROM (SELECT BOOK_ID, SUM(SALES) AS SALES_CNT 
      FROM BOOK_SALES 
      WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01'
      GROUP BY BOOK_ID) AS BOOK_TOTAL_SALES
JOIN BOOK USING(BOOK_ID)
JOIN AUTHOR USING(AUTHOR_ID)
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC;