WITH MILK_COUNT AS (
     SELECT CART_ID, COUNT(*)
     FROM CART_PRODUCTS
     WHERE NAME = 'Milk' 
     GROUP BY CART_ID
),
YOGURT_COUNT AS (
     SELECT CART_ID, COUNT(*)
     FROM CART_PRODUCTS
     WHERE NAME = 'Yogurt' 
     GROUP BY CART_ID
)
SELECT DISTINCT(CART_ID)
FROM CART_PRODUCTS AS CP
JOIN MILK_COUNT USING(CART_ID)
JOIN YOGURT_COUNT USING(CART_ID)