SELECT ED_THREE.ID
FROM ECOLI_DATA ED_ONE
JOIN ECOLI_DATA ED_TWO ON ED_ONE.ID = ED_TWO.PARENT_ID
JOIN ECOLI_DATA ED_THREE ON ED_TWO.ID = ED_THREE.PARENT_ID
WHERE ED_ONE.PARENT_ID is null
ORDER BY ID ASC