SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO AS II
WHERE ITEM_ID not in (SELECT DISTINCT(PARENT_ITEM_ID)
                  FROM ITEM_TREE
                  where PARENT_ITEM_ID is not null)
ORDER BY ITEM_ID DESC;
