(SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE
WHERE SALES_DATE like '2022-03-%'

UNION

SELECT SALES_DATE, PRODUCT_ID, NULL, SALES_AMOUNT
FROM OFFLINE_SALE
WHERE SALES_DATE like '2022-03-%')
ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC
