SELECT CC.CAR_ID, CC.CAR_TYPE, CAST((100 - DISCOUNT_RATE) * CC.DAILY_FEE * 30 / 100 AS SIGNED) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS CC
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS CP ON CC.CAR_TYPE = CP.CAR_TYPE AND CP.DURATION_TYPE = '30일 이상'
WHERE (CC.CAR_TYPE = '세단' or CC.CAR_TYPE = 'SUV') 
AND CC.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= '2022-11-30'
      AND END_DATE >= '2022-11-01'
)
AND (100 - DISCOUNT_RATE) * CC.DAILY_FEE * 30 / 100 >= 500000
AND (100 - DISCOUNT_RATE) * CC.DAILY_FEE * 30 / 100 < 2000000