WITH MAX_FAVORITE AS (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS MAX_FA
    FROM REST_INFO
    GROUP BY FOOD_TYPE
)

SELECT RI.FOOD_TYPE, RI.REST_ID, RI.REST_NAME, RI.FAVORITES
FROM REST_INFO RI
JOIN MAX_FAVORITE MF
ON RI.FOOD_TYPE = MF.FOOD_TYPE AND RI.FAVORITES = MF.MAX_FA
ORDER BY FOOD_TYPE DESC;
