WITH A AS 
(SELECT ID, RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS RANKING, (SELECT COUNT(*) FROM ECOLI_DATA) AS TOTAL
 FROM ECOLI_DATA
)

SELECT ID, CASE WHEN (RANKING * 100 / TOTAL) <= 25 THEN "CRITICAL"
            WHEN (RANKING * 100 / TOTAL) > 25 AND (RANKING * 100 / TOTAL) <= 50 THEN "HIGH"
            WHEN (RANKING * 100 / TOTAL) > 50 AND (RANKING * 100 / TOTAL) <= 75 THEN "MEDIUM"
            ELSE "LOW"
        END AS COLONY_NAME
FROM A
ORDER BY ID ASC;


# SELECT(ID, SIZE_OF_COLONY FROM ECOLI_DATA)