SELECT UGU.USER_ID, NICKNAME, 
    CONCAT(CONCAT(CONCAT(CONCAT(UGU.CITY, " "), UGU.STREET_ADDRESS1), " "), UGU.STREET_ADDRESS2)  AS 전체주소,
    INSERt(INSERT(UGU.TLNO, 4, 0, "-"), 9, 0, "-") AS 전화번호
FROM USED_GOODS_BOARD AS UGB
JOIN USED_GOODS_USER AS UGU ON UGB.WRITER_ID = UGU.USER_ID
GROUP BY UGU.USER_ID
HAVING COUNT(UGU.USER_ID) >= 3
ORDER BY UGU.USER_ID DESC;