SELECT ANIMAL_ID, AO.ANIMAL_TYPE, AO.NAME
FROM ANIMAL_OUTS AS AO
INNER JOIN ANIMAL_INS AS AI USING(ANIMAL_ID)
WHERE AI.SEX_UPON_INTAKE like '%Intact%' and (AO.SEX_UPON_OUTCOME like '%Spayed%' OR AO.SEX_UPON_OUTCOME like '%Neutered%');