SELECT RI.REST_ID, RI.REST_NAME, RI.FOOD_TYPE, RI.FAVORITES, RI.ADDRESS, TEMP.SCORE
FROM REST_INFO AS RI 
LEFT JOIN 
   (SELECT RR.REST_ID, ROUND(AVG(COALESCE(RR.REVIEW_SCORE, 0)), 2) AS SCORE
   FROM REST_REVIEW AS RR
   WHERE RR.REST_ID is NOT NULL
   GROUP BY RR.REST_ID) as TEMP
   ON TEMP.REST_ID = RI.REST_ID
WHERE RI.ADDRESS LIKE '서울%' AND TEMP.SCORE IS NOT NULL
ORDER BY TEMP.SCORE DESC, FAVORITES DESC;
