SELECT RI.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(RS.SCORE, 2) AS SCORE
FROM REST_INFO AS RI
JOIN (SELECT REST_ID, AVG(REVIEW_SCORE) AS SCORE FROM REST_REVIEW GROUP BY REST_ID) AS RS USING(REST_ID)
WHERE ADDRESS like '서울%'
ORDER BY SCORE DESC, FAVORITES DESC