-- 코드를 입력하세요
SELECT TO_CHAR(SALES_DATE, 'yyyy') as YEAR, TO_NUMBER(TO_CHAR(SALES_DATE, 'mm')) as MONTH, USER_INFO.GENDER, COUNT(distinct ONLINE_SALE.USER_ID) as USERS
FROM ONLINE_SALE
INNER JOIN USER_INFO
on ONLINE_SALE.USER_ID = USER_INFO.USER_ID and USER_INFO.GENDER is not null
GROUP BY TO_CHAR(SALES_DATE, 'yyyy'), TO_NUMBER(TO_CHAR(SALES_DATE, 'mm')), USER_INFO.GENDER
ORDER BY YEAR, MONTH, GENDER
