WITH A AS (
    SELECT COUNT(*) AS TOTAL
    FROM USER_INFO
    WHERE JOINED like '2021%'
)


SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, COUNT(DISTINCT UI.USER_ID) AS PURCHASED_USERS, ROUND(COUNT(DISTINCT UI.USER_ID) / TOTAL, 1) AS PUCHASED_RATIO
FROM USER_INFO AS UI
JOIN ONLINE_SALE AS OS ON UI.USER_ID = OS.USER_ID
CROSS JOIN A
WHERE JOINED like '2021%'
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY YEAR(SALES_DATE), MONTH(SALES_DATE)
