WITH RECURSIVE GEN_DATA AS (
    SELECT ID, PARENT_ID, 1 AS GEN
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL

    UNION ALL

    SELECT E.ID, E.PARENT_ID, GEN_DATA.GEN + 1
    FROM ECOLI_DATA E
    JOIN GEN_DATA ON E.PARENT_ID = GEN_DATA.ID
)

SELECT COUNT(*) AS "COUNT", GEN AS GENERATION
FROM ECOLI_DATA AS ED
JOIN GEN_DATA ON GEN_DATA.ID = ED.ID
WHERE ED.ID NOT IN (SELECT PARENT_ID FROM ECOLI_DATA where PARENT_ID IS NOT NULL)
GROUP BY GEN_DATA.GEN
ORDER BY GEN ASC;