SELECT *
FROM (
    SELECT AI.NAME, AI.DATETIME
    FROM ANIMAL_INS AS AI
    LEFT JOIN ANIMAL_OUTS AS AO USING(ANIMAL_ID)
    WHERE AO.DATETIME IS NULL
    ORDER BY AI.DATETIME ASC
    LIMIT 3
) AS OLDEST
ORDER BY DATETIME ASC;
