SELECT PRODUCT_ID, PRODUCT_NAME, SUM(AMOUNT * PRICE) AS TOTAL_SALES
FROM FOOD_ORDER
INNER JOIN FOOD_PRODUCT USING(PRODUCT_ID)
WHERE PRODUCE_DATE like '2022-05%'
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC;