WITH CAR_INFO AS (
    SELECT 
        H.HISTORY_ID,
        C.CAR_ID,
        DATEDIFF(H.END_DATE, H.START_DATE) + 1 AS RENT_DAYS,
        C.CAR_TYPE,
        C.DAILY_FEE,
        CASE
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 90 THEN '90일 이상'
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 30 THEN '30일 이상'
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 7 THEN '7일 이상'
            ELSE NULL
        END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_CAR C
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
      ON C.CAR_ID = H.CAR_ID
    WHERE C.CAR_TYPE = '트럭'
)

SELECT 
    CI.HISTORY_ID,
    ROUND(
        CI.RENT_DAYS * CI.DAILY_FEE * 
        (100 - IFNULL(DP.DISCOUNT_RATE, 0)) / 100
    ) AS FEE
FROM CAR_INFO CI
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP
  ON CI.CAR_TYPE = DP.CAR_TYPE
 AND CI.DURATION_TYPE = DP.DURATION_TYPE
ORDER BY FEE DESC, HISTORY_ID DESC;