SELECT UIC.FLAVOR 
FROM (
    SELECT SHIPMENT_ID, FLAVOR, TOTAL_ORDER
    FROM FIRST_HALF
UNION ALL
    SELECT SHIPMENT_ID, FLAVOR, TOTAL_ORDER
    FROM JULY
) AS UIC
GROUP BY UIC.FLAVOR
ORDER BY SUM(UIC.TOTAL_ORDER) DESC
LIMIT 3;

