-- 코드를 입력하세요
SELECT APNT_NO, PT_NAME, PT_NO, APPOINTMENT.MCDP_CD, DR_NAME, APNT_YMD
FROM PATIENT 
JOIN APPOINTMENT USING(PT_NO) JOIN DOCTOR ON DOCTOR.DR_ID = APPOINTMENT.MDDR_ID
WHERE APNT_CNCL_YN = 'N' 
    AND DATE_FORMAT(APNT_YMD, '%Y-%m-%d') = '2022-04-13'
ORDER BY APNT_YMD ASC;