SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW
JOIN MEMBER_PROFILE USING(MEMBER_ID)
WHERE MEMBER_ID = (
                    SELECT MEMBER_ID
                    FROM REST_REVIEW
                    GROUP BY MEMBER_ID
                    ORDER BY COUNT(*) DESC
                    limit 1
                  )
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC
