WITH ITEM_TOTAL_INFO AS 
(SELECT *
FROM ITEM_INFO II
JOIN ITEM_TREE IT USING(ITEM_ID))

SELECT PI.ITEM_ID, PI.ITEM_NAME, PI.RARITY
FROM ITEM_TOTAL_INFO CI
JOIN ITEM_TOTAL_INFO PI on CI.ITEM_ID = PI.PARENT_ITEM_ID
WHERE CI.RARITY = 'RARE'
ORDER BY PI.ITEM_ID DESC
