WITH MAX_DATA AS (
SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
FROM ECOLI_DATA
GROUP BY YEAR(DIFFERENTIATION_DATE)
)

SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX_DATA.MAX_SIZE - SIZE_OF_COLONY AS YEAR_DEV, ID
FROM ECOLI_DATA AS E
JOIN MAX_DATA ON YEAR(E.DIFFERENTIATION_DATE) = MAX_DATA.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC;