SELECT DISTINCT(CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR AS CR
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CRH USING(CAR_ID)
WHERE MONTH(CRH.START_DATE) = 10
    AND CAR_TYPE = '세단'
ORDER BY CAR_ID DESC;