

SELECT HR_SUM_GRADE.SCORE, HR_EMPLOYEES.EMP_NO, 
    HR_EMPLOYEES.EMP_NAME, HR_EMPLOYEES.POSITION, HR_EMPLOYEES.EMAIL
FROM (
    SELECT EMP_NO, SUM(SCORE) AS SCORE
    FROM HR_GRADE
    WHERE YEAR = '2022'
    GROUP BY EMP_NO
    ) AS HR_SUM_GRADE
JOIN HR_EMPLOYEES ON HR_EMPLOYEES.EMP_NO = HR_SUM_GRADE.EMP_NO
ORDER BY SCORE DESC
LIMIT 1;