WITH EMPLOYEES_AVG AS (
  SELECT DEPT_ID, ROUND(AVG(SAL)) AS AVG_SAL
  FROM HR_EMPLOYEES
  GROUP BY DEPT_ID
)

SELECT HD.DEPT_ID, HD.DEPT_NAME_EN, EA.AVG_SAL
FROM HR_DEPARTMENT AS HD
JOIN EMPLOYEES_AVG AS EA USING(DEPT_ID)
ORDER BY AVG_SAL DESC;
