WITH MAX_CATEGORY AS (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY in ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
)

SELECT FP.CATEGORY, MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT AS FP
JOIN MAX_CATEGORY AS MC ON FP.CATEGORY =  MC.CATEGORY AND FP.PRICE = MC.MAX_PRICE
ORDER BY MAX_PRICE DESC


