WITH FIX_FISH_INFO AS (
    SELECT ID, FISH_TYPE, CASE 
                            WHEN LENGTH is null THEN 10
                            ELSE LENGTH 
                           END AS LENGTH, TIME
    FROM FISH_INFO
)

SELECT COUNT(*) AS FISH_COUNT, MAX(LENGTH) as MAX_LENGTH, FISH_TYPE
FROM FIX_FISH_INFO
GROUP BY FISH_TYPE HAVING AVG(LENGTH) >= 33
ORDER BY FISH_TYPE;