WITH CODE_DATA AS (
    SELECT
        MAX(CASE WHEN NAME = 'Python' THEN CODE END) AS PYTHON_CODE,
        MAX(CASE WHEN NAME = 'C#' THEN CODE END) AS CSHARP_CODE,
        SUM(CASE WHEN CATEGORY = 'Front End' THEN CODE ELSE 0 END) AS FRONTEND_CODE
    FROM SKILLCODES
),
GT AS (
    SELECT
        D.ID,
        D.EMAIL,
        CASE
            WHEN (D.SKILL_CODE & C.PYTHON_CODE) != 0
                 AND (D.SKILL_CODE & C.FRONTEND_CODE) != 0 THEN 'A'
            WHEN (D.SKILL_CODE & C.CSHARP_CODE) != 0 THEN 'B'
            WHEN (D.SKILL_CODE & C.FRONTEND_CODE) != 0 THEN 'C'
            ELSE NULL
        END AS GRADE
    FROM DEVELOPERS D, CODE_DATA C
)

SELECT GRADE, ID, EMAIL
FROM GT
WHERE GRADE IS NOT NULL
ORDER BY GRADE, ID;