SELECT B.BOOK_ID, A.AUTHOR_NAME, DATE_FORMAT(B.PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK AS B
INNER JOIN AUTHOR AS A on B.AUTHOR_ID = A.AUTHOR_ID
WHERE B.CATEGORY = '경제' 
ORDER BY PUBLISHED_DATE;